export const ARTICLE_THREAD_REQUEST = 'ARTICLE_THREAD_REQUEST';
export const ARTICLE_THREAD_SUCCESS = 'ARTICLE_THREAD_SUCCESS';
export const ARTICLE_THREAD_FAILURE = 'ARTICLE_THREAD_FAILURE';
export const CLEAR_REDIRECT = 'CLEAR_REDIRECT';
