export const ARTICLE_THREAD_REQUEST = 'ARTICLE_THREAD_REQUEST';
export const ARTICLE_THREAD_SUCCESS = 'ARTICLE_THREAD_SUCCESS';
export const ARTICLE_THREAD_FAILURE = 'ARTICLE_THREAD_FAILURE';
export const CLEAR_REDIRECT = 'CLEAR_REDIRECT';

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAILURE = 'POST_COMMENT_FAILURE';
