export const BOOKMARK_ARTICLE_REQUEST = 'BOOKMARK_ARTICLE_REQUEST';
export const BOOKMARK_ARTICLE_SUCCESS = 'BOOKMARK_ARTICLE_SUCCESS';
export const BOOKMARK_ARTICLE_FAILURE = 'BOOKMARK_ARTICLE_FAILURE';
export const UNBOOKMARK_ARTICLE_REQUEST = 'UNBOOKMARK_ARTICLE_REQUEST';
export const UNBOOKMARK_ARTICLE_SUCCESS = 'UNBOOKMARK_ARTICLE_SUCCESS';
export const UNBOOKMARK_ARTICLE_FAILURE = 'UNBOOKMARK_ARTICLE_FAILURE';
