const REGISTER_REQUEST = 'REGISTER_REQUEST';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILURE = 'REGISTER_FAILURE';

export {
  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE
};
