export const TRENDING_ARTICLES_REQUEST = 'TRENDING_ARTICLES_REQUEST';
export const TRENDING_ARTICLES_SUCCESS = 'TRENDING_ARTICLES_SUCCESS';
export const TRENDING_ARTICLES_FAILURE = 'TRENDING_ARTICLES_FAILURE';
