const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';
const USER_BOOKMARK_REQUEST = 'USER_BOOKMARK_REQUEST';
const USER_BOOKMARK_SUCCESS = 'USER_BOOKMARK_SUCCESS';
const USER_BOOKMARK_FAILURE = 'USER_BOOKMARK_FAILURE';
const UPDATE_USER_IMAGE = 'UPDATE_USER_IMAGE';
const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

export {
  USER_PROFILE_REQUEST,
  USER_PROFILE_SUCCESS,
  USER_PROFILE_FAILURE,
  USER_BOOKMARK_FAILURE,
  USER_BOOKMARK_REQUEST,
  USER_BOOKMARK_SUCCESS,
  UPDATE_USER_IMAGE,
  EDIT_PROFILE_REQUEST,
  EDIT_PROFILE_SUCCESS,
  EDIT_PROFILE_FAILURE
};
