const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';
const USER_BOOKMARK_REQUEST = 'USER_BOOKMARK_REQUEST';
const USER_BOOKMARK_SUCCESS = 'USER_BOOKMARK_SUCCESS';
const USER_BOOKMARK_FAILURE = 'USER_BOOKMARK_FAILURE';

export {
  USER_PROFILE_REQUEST,
  USER_PROFILE_SUCCESS,
  USER_PROFILE_FAILURE,
  USER_BOOKMARK_FAILURE,
  USER_BOOKMARK_REQUEST,
  USER_BOOKMARK_SUCCESS
};
